steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build container image'
  args: [
    'build',
    '.',
    '-t',
    'europe-west1-docker.pkg.dev/eighth-saga-484310-f8/wikiart-registry/wikiart-evaluate:latest',
    '-f',
    './dockerfiles/evaluate.dockerfile'
  ]

- name: 'gcr.io/cloud-builders/docker'
  id: 'Push container image'
  args: [
    'push',
    'europe-west1-docker.pkg.dev/eighth-saga-484310-f8/wikiart-registry/wikiart-evalaute:latest'
  ]

- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Deploy to Cloud Run'
  args: [
    'run',
    'deploy',
    'wikiart-evaluate',
    '--image',
    'europe-west1-docker.pkg.dev/eighth-saga-484310-f8/wikiart-registry/wikiart-evaluate:latest',
    '--region',
    'europe-west1',
    '--platform',
    'managed',
    '--execution-environment',
    'gen2',
    '--allow-unauthenticated'
  ]

options:
  logging: CLOUD_LOGGING_ONLY
